### ISSUE TITLE
improve error msg when importing faucet in mockup mode

### ISSUE THREAD

**Issue by rognierbenoit** [edukera/completium-cli#19]

**Comment by rognierbenoit** [comment]
```? cryptoeasy_admin already exists, do you want to overwrite? Yes
Importing key ...
Error: Unsupported protocol null
    at new NetworkError (/Users/benoitrognier/.nvm/versions/node/v14.18.0/lib/node_modules/@completium/completium-cli/node_modules/xhr2-cookies/dist/errors.js:32:42)
    at XMLHttpRequest.send (/Users/benoitrognier/.nvm/versions/node/v14.18.0/lib/node_modules/@completium/completium-cli/node_modules/xhr2-cookies/dist/xml-http-request.js:156:23)
    at /Users/benoitrognier/.nvm/versions/node/v14.18.0/lib/node_modules/@completium/completium-cli/node_modules/@taquito/http-utils/dist/taquito-http-utils.umd.js:455:27
    at new Promise (<anonymous>)
    at HttpBackend.createRequest (/Users/benoitrognier/.nvm/versions/node/v14.18.0/lib/node_modules/@completium/completium-cli/node_modules/@taquito/http-utils/dist/taquito-http-utils.umd.js:413:18)
    at RpcClient.<anonymous> (/Users/benoitrognier/.nvm/versions/node/v14.18.0/lib/node_modules/@completium/completium-cli/node_modules/@taquito/rpc/dist/taquito-rpc.umd.js:546:71)
    at step (/Users/benoitrognier/.nvm/versions/node/v14.18.0/lib/node_modules/@completium/completium-cli/node_modules/@taquito/rpc/dist/taquito-rpc.umd.js:81:27)
    at Object.next (/Users/benoitrognier/.nvm/versions/node/v14.18.0/lib/node_modules/@completium/completium-cli/node_modules/@taquito/rpc/dist/taquito-rpc.umd.js:62:57)
    at /Users/benoitrognier/.nvm/versions/node/v14.18.0/lib/node_modules/@completium/completium-cli/node_modules/@taquito/rpc/dist/taquito-rpc.umd.js:55:75
    at new Promise (<anonymous>)```
